# Generated by Django 4.0.2 on 2022-02-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlog', '0005_catagory_post_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
