# Generated by Django 4.0.2 on 2022-02-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlog', '0014_profile_email_url_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_url',
        ),
    ]
